from pathlib import Path

path = Path(r"C:\Users\cerul\ParkWise\src\app.py")
text = path.read_text()
old = "        stats = {}\n        \n        # Total violations\n        total_query = \"SELECT COUNT(*) as total FROM Ticket\"\n        total_df = pd.read_sql(total_query, conn)\n        stats['totalViolations'] = total_df.iloc[0]['total']\n        print(f\"[DEBUG] /api/statistics => totalViolations={stats['totalViolations']}\")\n\n        # Most common violations\n        violations_query = \"\"\"\n        SELECT TOP 5\n            v.Description as violation_type,\n            COUNT(*) as count,\n            v.Cost as fine\n        FROM Ticket t\n        JOIN Violation v ON t.violation_code = v.Code\n        GROUP BY v.Description, v.Cost\n        ORDER BY COUNT(*) DESC\n        \"\"\"\n        stats['topViolations'] = pd.read_sql(violations_query, conn).to_dict('records')\n\n        # Peak hours\n        peak_hours_query = \"\"\"\n        SELECT TOP 5\n            DATEPART(HOUR, issue_date) as hour,\n            COUNT(*) as count\n        FROM Ticket\n        WHERE issue_date IS NOT NULL\n        GROUP BY DATEPART(HOUR, issue_date)\n        ORDER BY COUNT(*) DESC\n        \"\"\"\n        stats['peakHours'] = pd.read_sql(peak_hours_query, conn).to_dict('records')\n\n        # Hottest locations\n        hot_locations_query = \"\"\"\n        SELECT TOP 10\n            violation_location,\n            COUNT(*) as count\n        FROM Ticket\n        WHERE violation_location IS NOT NULL\n        GROUP BY violation_location\n        ORDER BY COUNT(*) DESC\n        \"\"\"\n        stats['hotLocations'] = pd.read_sql(hot_locations_query, conn).to_dict('records')\n\n        conn.close()\n\n        return jsonify({\n            'status': 'success',\n            'data': stats\n        })"
if old not in text:
    raise SystemExit('old statistics block not found')
new = "        stats = {}\n\n        # Total violations\n        total_query = \"SELECT COUNT(*) as total FROM Ticket\"\n        total_df = pd.read_sql(total_query, conn)\n        stats['totalViolations'] = safe_int(total_df.iloc[0]['total'])\n        print(f\"[DEBUG] /api/statistics => totalViolations={stats['totalViolations']}\")\n\n        # Most common violations\n        violations_query = \"\"\"\n        SELECT TOP 5\n            v.Description as violation_type,\n            COUNT(*) as count,\n            v.Cost as fine\n        FROM Ticket t\n        JOIN Violation v ON t.violation_code = v.Code\n        GROUP BY v.Description, v.Cost\n        ORDER BY COUNT(*) DESC\n        \"\"\"\n        top_violations_df = pd.read_sql(violations_query, conn)\n        stats['topViolations'] = []\n        for record in top_violations_df.to_dict('records'):\n            stats['topViolations'].append({\n                'violation_type': record['violation_type'],\n                'count': safe_int(record['count']),\n                'fine': safe_float(record['fine'])\n            })\n\n        # Peak hours\n        peak_hours_query = \"\"\"\n        SELECT TOP 5\n            DATEPART(HOUR, issue_date) as hour,\n            COUNT(*) as count\n        FROM Ticket\n        WHERE issue_date IS NOT NULL\n        GROUP BY DATEPART(HOUR, issue_date)\n        ORDER BY COUNT(*) DESC\n        \"\"\"\n        peak_hours_df = pd.read_sql(peak_hours_query, conn)\n        stats['peakHours'] = []\n        for record in peak_hours_df.to_dict('records'):\n            stats['peakHours'].append({\n                'hour': safe_int(record['hour']),\n                'count': safe_int(record['count'])\n            })\n\n        # Hottest locations\n        hot_locations_query = \"\"\"\n        SELECT TOP 10\n            violation_location,\n            COUNT(*) as count\n        FROM Ticket\n        WHERE violation_location IS NOT NULL\n        GROUP BY violation_location\n        ORDER BY COUNT(*) DESC\n        \"\"\"\n        hot_locations_df = pd.read_sql(hot_locations_query, conn)\n        stats['hotLocations'] = []\n        for record in hot_locations_df.to_dict('records'):\n            stats['hotLocations'].append({\n                'violation_location': record['violation_location'],\n                'count': safe_int(record['count'])\n            })\n\n        conn.close()\n\n        return jsonify({\n            'status': 'success',\n            'data': stats\n        })"
text = text.replace(old, new)
path.write_text(text)
